[theme]

# Primary accent for interactive elements
primaryColor = '#FFFFFF'

# Background color for the main content area
backgroundColor = '#00172B'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#202020'

# Color used for almost all text
textColor = '#E0E0E0'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"
font = "arial"